### ISSUE TITLE
oil-rig icon

### ISSUE THREAD

**Issue by Alex3k** [elastic/maki#5]
#### Icon Request
Specific use case prompting request - Displaying oil rigs on a map, very useful for trying to encourage the oil industry to use our maps application

Icon concept & Reference Images:
[Example One ](https://t3.ftcdn.net/jpg/00/74/96/08/500_F_74960812_jYExS4hptO45OA7PpjMTyhw8bF1MyVMY.jpg)
[Example Two](https://cdn4.iconfinder.com/data/icons/energy-4/32/Energy-icons_oil-rig-512.png)

**Comment by nreese** [comment]
@ryankeairns Would you be able to create another icon for us?

**Comment by ryankeairns** [comment]
Yep, I'll try and get to this in the next or so.
